<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateSusersGroupsRelationshipTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('susers_groups_relationship', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->unsignedBigInteger('suser_id');
            $table->unsignedBigInteger('sgroup_id');

            $table->index('suser_id', 'suser_id');
            $table->index('sgroup_id', 'sgroup_id');

            $table->foreign('sgroup_id', 'susers_groups_relationship_ibfk_1')->references('id')->on('sgroups')->onDelete('RESTRICT
')->onUpdate('CASCADE');
            $table->foreign('suser_id', 'susers_groups_relationship_ibfk_2')->references('id')->on('susers')->onDelete('CASCADE
')->onUpdate('CASCADE');

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('susers_groups_relationship');
    }
}
